namespace DTS
{
    [default_interface] runtimeclass Selector : Microsoft.UI.Xaml.Controls.DataTemplateSelector
    {
        Selector();
    
        Microsoft.UI.Xaml.DataTemplate firstTemplate;
        Microsoft.UI.Xaml.DataTemplate secondTemplate;
    }
}
